sudo: required
services:
  - docker
language: python
python:
  - "3.8"
before_install:
  - cd backend
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source="auth/","library/" -m unittest
after_script:
  - coveralls
  - pylint backend --ignore=migrations --load-plugins=pylint_flask,pylint_flask_sqlalchemy
#after_success:
#  - sh .travis/deploy_dockerhub.sh
