sudo: required
services:
  - docker
language: python
python:
  - "3.8"
before_install:
  - cd backend
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source="." -m unittest && coveralls
  - coverage report --fail-under=80
  - cd ../ && pylint backend --ignore=migrations --rcfile=backend/.pylintrc --fail-under=9
#after_success:
#  - sh .travis/deploy_dockerhub.sh
