version: '3'

services:
    api:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
#        command: python -m gunicorn --workers 3 --bind 0.0.0.0:5000 manage:app
        command: python manage.py runserver -h 0.0.0.0 -p 5000
        environment:
            - CACHE_REDIS_URL=redis://redis:6379
            - PROD_DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
        volumes:
            - ./backend:/api
        depends_on:
            - db
            - redis

    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - ./backend/database:/api/database

    redis:
        image: redis
        ports:
            - "6379:6379"

    client:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/client
        depends_on:
            - api