version: '3'

services:
    api:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        command: python manage.py runserver -h 0.0.0.0 -p 5000
        environment:
            - FlASK_APP=manage.py
            - FLASK_ENV=development
            - ELASTICSEARCH_URL=http://elasticsearch:9200
            - CELERY_BROKER_URL=redis://redis:6379
            - CELERY_RESULT_BACKEND=redis://redis:6379
        volumes:
            - ./backend:/api
        depends_on:
            - redis
            - elasticsearch
            - migration

    worker:
        build:
            context: ./backend
            dockerfile: Dockerfile
        command: celery --app=celery_worker.celery worker --loglevel=info
        volumes:
            - ./backend:/api
        environment:
            - CELERY_BROKER_URL=redis://redis:6379
            - CELERY_RESULT_BACKEND=redis://redis:6379
        depends_on:
            - api
            - redis

    migration:
        build:
            context: ./backend
            dockerfile: Dockerfile
        command: python manage.py db upgrade
        environment:
            - FLASK_ENV=development
        volumes:
            - ./backend:/api

    redis:
        image: redis
        ports:
            - "6379:6379"

    elasticsearch:
        image: elasticsearch:7.5.2
        ports:
            - "9200:9200"
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        volumes:
            - ./backend/elasticsearch:/api/elasticsearch


    client:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - ./frontend:/client
        depends_on:
            - api